# Generated by Django 5.2.16 on 2026-07-26 16:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_location_text', models.CharField(max_length=255)),
                ('pickup_location_text', models.CharField(max_length=255)),
                ('dropoff_location_text', models.CharField(max_length=255)),
                ('cycle_hours_used', models.DecimalField(decimal_places=2, max_digits=5)),
                ('trip_start_time', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('planned', 'Planned'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('total_distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('total_duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['created_at'], name='planning_tr_created_69f1a9_idx'), models.Index(fields=['status'], name='planning_tr_status_851f24_idx'), models.Index(fields=['trip_start_time'], name='planning_tr_trip_st_9d0245_idx')],
            },
        ),
        migrations.CreateModel(
            name='TimelineEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('duty_status', models.CharField(choices=[('off_duty', 'Off Duty'), ('sleeper_berth', 'Sleeper Berth'), ('driving', 'Driving'), ('on_duty_not_driving', 'On Duty (Not Driving)')], max_length=25)),
                ('event_type', models.CharField(choices=[('drive', 'Drive'), ('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest_break_30', 'Rest Break (30-min)'), ('daily_rest_10', 'Daily Rest (10-hr)'), ('cycle_restart_34', 'Cycle Restart (34-hr)'), ('pretrip_inspection', 'Pre-Trip Inspection'), ('posttrip_inspection', 'Post-Trip Inspection')], max_length=25)),
                ('location_name', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('distance_miles', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('reason', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_events', to='planning.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_event_sequence')],
            },
        ),
        migrations.CreateModel(
            name='RouteLeg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField()),
                ('leg_type', models.CharField(choices=[('deadhead', 'Deadhead'), ('loaded', 'Loaded')], max_length=20)),
                ('origin_text', models.CharField(max_length=255)),
                ('destination_text', models.CharField(max_length=255)),
                ('distance_miles', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('encoded_polyline', models.TextField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='route_legs', to='planning.trip')),
            ],
            options={
                'ordering': ['sequence'],
                'constraints': [models.UniqueConstraint(fields=('trip', 'sequence'), name='unique_trip_leg_sequence')],
            },
        ),
    ]
